name: "Continuous Deployment"

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    runs-on: "ubuntu-18.04"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint AssemblyScript code"
        run: "yarn run lint"

      - name: "Generate subgraph manifest"
        run: "yarn run prepare:mainnet"

      - name: "Generate AssemblyScript types"
        run: "yarn run codegen"

      - name: "Deploy to Goerli"
        run: yarn run deploy:goerli --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Kovan"
        run: yarn run deploy:kovan --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Rinkeby"
        run: yarn run deploy:rinkeby --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Ropsten"
        run: yarn run deploy:ropsten --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Mainnet"
        run: yarn run deploy:mainnet --access-token ${{ secrets.THE_GRAPH_TOKEN }}
