name: "Continuous Deployment"

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    runs-on: "macos-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          node-version: "14"

      - name: "Load cache if any"
        uses: "actions/cache@v2"
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          path: "./node_modules"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint AssemblyScript code"
        run: "yarn run lint"

      - name: "Generate AssemblyScript types"
        run: |
          yarn run prepare:mainnet
          yarn run codegen

      - name: "Deploy to Goerli"
        run: yarn run deploy:goerli --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Kovan"
        run: yarn run deploy:kovan --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Rinkeby"
        run: yarn run deploy:rinkeby --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Ropsten"
        run: yarn run deploy:ropsten --access-token ${{ secrets.THE_GRAPH_TOKEN }}

      - name: "Deploy to Mainnet"
        run: yarn run deploy:mainnet --access-token ${{ secrets.THE_GRAPH_TOKEN }}
